// SquadAITypes.h
// Shared data types for the Squad AI system. No logic here, just the vocabulary
// the rest of the module speaks.

#pragma once

#include "CoreMinimal.h"
#include "SquadAITypes.generated.h"

class AAISquadController;

// Tactical role a squad member is currently assigned. Roles are arbitrated by
// USquadCoordinatorComponent so that, e.g., only one bot flanks at a time.
UENUM(BlueprintType)
enum class ESquadRole : uint8
{
	None,
	Suppressing,	// Holding an enemy's attention with sustained fire from current position
	Flanking,		// Moving to a side/rear angle on the last known enemy position
	Advancing,		// Pushing toward the enemy's position under covering fire
	Retreating,		// Falling back to regroup (e.g. low health, no ammo, overwhelmed)
	Reloading		// Temporarily out of the fight, seeking cover to reload
};

// A single enemy sighting shared across the squad. Distinct from what an
// individual bot's AIPerception knows locally.
USTRUCT(BlueprintType)
struct FSquadEnemyKnowledge
{
	GENERATED_BODY()

	UPROPERTY(BlueprintReadOnly)
	TWeakObjectPtr<AActor> Enemy;

	UPROPERTY(BlueprintReadOnly)
	FVector LastKnownLocation = FVector::ZeroVector;

	UPROPERTY(BlueprintReadOnly)
	float LastSeenTimestamp = 0.f;

	// True while at least one squad member currently has direct line of sight.
	UPROPERTY(BlueprintReadOnly)
	bool bCurrentlyVisible = false;

	// Instance ID of the squad member that last reported this sighting, so we
	// can avoid a bot "confirming" its own stale report as corroboration.
	UPROPERTY(BlueprintReadOnly)
	int32 ReportedByControllerId = INDEX_NONE;
};

// Snapshot of one squad member's state, as seen by the coordinator and by
// other bots deciding whether to e.g. flank alongside them.
USTRUCT(BlueprintType)
struct FSquadMemberState
{
	GENERATED_BODY()

	UPROPERTY(BlueprintReadOnly)
	TWeakObjectPtr<AAISquadController> Controller;

	UPROPERTY(BlueprintReadOnly)
	ESquadRole CurrentRole = ESquadRole::None;

	UPROPERTY(BlueprintReadOnly)
	float HealthFraction = 1.f;

	UPROPERTY(BlueprintReadOnly)
	int32 AmmoCount = 0;

	UPROPERTY(BlueprintReadOnly)
	FVector Location = FVector::ZeroVector;
};

// One candidate cover point, as generated by UCoverPointSubsystem.
USTRUCT(BlueprintType)
struct FCoverPointData
{
	GENERATED_BODY()

	UPROPERTY(BlueprintReadOnly)
	FVector Location = FVector::ZeroVector;

	// Direction the cover faces (i.e. the direction the obstacle is in, relative
	// to Location). A bot standing at Location and firing should lean out
	// roughly perpendicular to this.
	UPROPERTY(BlueprintReadOnly)
	FVector FacingDirection = FVector::ForwardVector;

	// Whether this point still has an unobstructed line back toward the last
	// known enemy location. Recomputed on demand, not cached long-term, since
	// enemies move.
	UPROPERTY(BlueprintReadOnly)
	bool bProvidesCoverFromLastKnownEnemy = false;

	// Controller currently claiming this point, if any. Prevents two bots
	// from converging on the same piece of cover.
	UPROPERTY(BlueprintReadOnly)
	TWeakObjectPtr<AAISquadController> ClaimedBy;
};
